name: flutter_maps
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.0.0
  flutter_map_tile_caching: ^6.2.0
  geocode: ^1.0.2
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  flutter_speed_dial: ^6.2.0
  validators: ^3.0.0
  intl: ^0.17.0
  latlong2: ^0.8.1
  location_api_client:
    path: packages/location_api_client
  locations_repository:
    path: packages/locations_repository
  path: ^1.8.1

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
