name: locations_repository
description: Flutter package that handles locations related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  location_api_client:
    path: ../location_api_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
