name: location_api_client
description: Flutter package that handles location api requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.0
  very_good_analysis: ^3.0.0
